name: flutter_mapbox_navigation
description: >
  Add Turn By Turn Navigation to Your Flutter Application Using MapBox. 
  Never leave your app when you need to navigate your users to a location.
version: 0.2.2
homepage: "https://www.eopeter.com"
repository: "https://github.com/eopeter/flutter_mapbox_navigation"

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.eopeter.fluttermapboxnavigation
        pluginClass: FlutterMapboxNavigationPlugin
      ios:
        pluginClass: FlutterMapboxNavigationPlugin
 #      linux:
 #        pluginClass: FlutterMapboxNavigationPlugin
 #      macos:
 #        pluginClass: FlutterMapboxNavigationPlugin
 #      windows:
 #        pluginClass: FlutterMapboxNavigationPluginCApi
 #      web:
 #        pluginClass: FlutterMapboxNavigationWeb
 #        fileName: flutter_mapbox_navigation_web.dart
